pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Check out your code from Git
                checkout scm
            }
        }

        stage('Build') {
            steps {
                // Build your Spring Boot application (e.g., using Maven)
                sh 'mvn clean package'
            }
        }

        stage('Docker Build and Deploy') {
            steps {
                // Build a Docker image from your application code
                sh 'docker build -t emp-system .'
                
                // Run the Docker container
                sh 'docker run -d -p 8080:8080 --name emp-system-container emp-system'
            }
        }
    }
}
